### ISSUE TITLE
data/hz

### ISSUE THREAD

**Issue by HHHYAO1** [auntlemon/Traffic-Flow-Prediction#1]
你好，data/hz/中4个.txt文件和.pkl文件时如何得到的？

**Comment by auntlemon** [comment]
你好，是真实跑的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "auntlemon/Traffic-Flow-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 晚上8:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[auntlemon/Traffic-Flow-Prediction] data/hz (#1)





 
你好，data/hz/中4个.txt文件和.pkl文件时如何得到的？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HHHYAO1** [comment]
> 你好，是真实跑的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "auntlemon/Traffic-Flow-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2021年9月7日(星期二) 晚上8:49 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[auntlemon/Traffic-Flow-Prediction] data/hz (#1) 你好，data/hz/中4个.txt文件和.pkl文件时如何得到的？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HHHYAO1** [comment]
你好，这几个文件我应该运行什么脚本得到的？能用自己的地图数据吗？

**Comment by auntlemon** [comment]
只要把自己的数据集处理成代码中那样就可以用了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "auntlemon/Traffic-Flow-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [auntlemon/Traffic-Flow-Prediction] data/hz (#1)





 
你好，这几个文件我应该运行什么脚本得到的？能用自己的地图数据吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
